language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t thuongthanhto/wheel-app -f Dockerfile.dev .

script:
  - docker run -e CI=true thuongthanhto/wheel-app npm run test

after_success:
  - docker build -t thuongthanhto/wheel-app .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push thuongthanhto/wheel-app
